# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gestionrestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nom', models.CharField(max_length=255)),
                ('id_menu', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
    ]
