# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionrestaurant',
            name='id_menu',
        ),
    ]
