# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionrestaurant', '0002_remove_gestionrestaurant_id_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionrestaurant',
            old_name='id_nom',
            new_name='nom',
        ),
    ]
